runtime: nodejs:22
stages:
  build:
      commands:
            - npm ci
                  - npm run build
                      artifacts:
                            paths:
                                    - out/
                                    ignoredPaths:
                                      - node_modules
                                        - .env
                                          - .env.local
                                            - .env.*.local
                                              - .git
                                                - .github
