runtime: nodejs:22
stages:
  build:
      commands:
            - npm ci
                  - npm run build
                  ignoredPaths:
                    - node_modules
                      - .env
                        - .env.local
                          - .env.*.local
                            - .git
                              - .github
